name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      # Install dependencies
      - run: npm install
      
      # Build the project (ensure that this outputs to the "dist" folder)
      - run: npm run build
      
      # Upload the built "dist" folder as an artifact for the next job
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with full history (needed for branch switching)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Download the built "dist" folder from the previous job
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      # Switch to the target release branch (creating it if necessary)
      - name: Switch to release branch
        run: |
          # Try to check out the branch; if it doesn't exist, create it as an orphan branch.
          if git show-ref --verify --quiet refs/heads/release-branch; then
            git checkout release-branch
            git rm -rf . > /dev/null 2>&1 || true
          else
            git checkout --orphan release-branch
            git rm -rf . > /dev/null 2>&1 || true
          fi

      # Copy the contents of the "dist" folder to the repository root
      - name: Copy dist files to root
        run: |
          cp -R dist/* .
      
      # Commit and push the changes to the release branch
      - name: Commit and push built files
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          # Use "--allow-empty" to avoid failure if there are no changes.
          git commit -m "Deploy built files from commit ${{ github.sha }}" --allow-empty
          git push origin release-branch --force
