name: Build and Deploy

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3) Install and build
      - run: npm install
      - run: npm run build

      # 4) Copy assets to dist folder
      - name: Copy assets
        run: cp -r src/assets dist/

      # 5) Upload "dist" as artifact
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo with full history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Download the dist artifact to a temp folder
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: _dist_artifact

      # 3) Debug step – confirm downloaded build output
      - name: List downloaded files
        run: ls -R _dist_artifact

      # 4) Switch to (or create) the "releases" branch and remove old files
      - name: Switch to releases branch
        run: |
          if git show-ref --verify --quiet refs/heads/releases; then
            git checkout releases
          else
            git checkout --orphan releases
          fi

          # Remove tracked files in this branch
          git rm -rf . || true

          # Remove any leftover untracked files except .git and _dist_artifact
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '_dist_artifact' -exec rm -rf {} +

      # 5) Copy built files into repo root
      - name: Copy dist to root
        run: cp -R _dist_artifact/* .

      # 6) Commit and push built files
      - name: Commit and push built files
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Deploy built files from commit ${{ github.sha }}" --allow-empty
          git push origin releases --force
